import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Main_Layout from "@/components/layouts/Main_Layout";
import SessionProvider from "@/components/SessionProvider";

import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    const session = await getServerSession(authOptions);

    return (
        <html lang="en">
            <SessionProvider session={session}>
                <body className={inter.className}>
                    <Main_Layout>{children}</Main_Layout>
                </body>
            </SessionProvider>
        </html>
    );
}
